name: Process Claims Queue

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:         # allow manual run from Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # 🚫 remove cache completely — avoids lockfile check
          check-latest: true

      - name: Install deps (no build)
        run: npm install --no-audit --no-fund

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Process one queued claim
        run: node scripts/process-queue.mjs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUBMIT_LIVE: ${{ secrets.SUBMIT_LIVE }}
          PLAYWRIGHT_ENABLED: ${{ secrets.PLAYWRIGHT_ENABLED }}

      - name: Upload Playwright screenshots
        uses: actions/upload-artifact@v4
        with:
          name: avanti-screens
          path: |
            avanti_before.png
            avanti_after.png
        if: always()
